const JSON_HEADERS={"content-type":"application/json; charset=utf-8"};
const MAX_SKEW=10*60*1000;const ALL_SCOPES=new Set(['test:read','validation:read','passport:read','reputation:read']);
export async function handleDeveloper(request,env,url=new URL(request.url)){
  if(!url.pathname.startsWith('/api/v1/developer/'))return null;
  if(request.method==='GET'&&url.pathname==='/api/v1/developer/capabilities')return reply({service:'AccordTrace Developer Access',version:'0.1.0',features:['passport_signed_key_issuance','hash_only_key_storage','scoped_test_keys','key_revocation','enforced_test_ping'],test_mode:true,live_api_keys_enabled:String(env.LIVE_API_KEYS_ENABLED||'').toLowerCase()==='true'});
  if(request.method==='POST'&&url.pathname==='/api/v1/developer/keys'){
    const b=await bodyJson(request);const passport=await activePassport(env,b.passport_id);if(!passport)return reply({error:'passport_not_found'},404);
    const environment=String(b.environment||'test');if(!['test','live'].includes(environment))return reply({error:'invalid_environment'},400);if(environment==='live'&&String(env.LIVE_API_KEYS_ENABLED||'').toLowerCase()!=='true')return reply({error:'live_api_keys_disabled'},403);
    const scopes=normalizeScopes(b.scopes);required(b.request_id,'request_id');required(b.issued_at,'issued_at');required(b.signature,'signature');assertFresh(b.issued_at);
    const payload={domain:'accordtrace.developer.api_key.create.v1',request_id:cleanId(b.request_id),passport_id:passport.id,environment,scopes,issued_at:new Date(b.issued_at).toISOString()};await verifyEd25519(passport.public_key,canonicalize(payload),b.signature);
    const exists=await env.DB.prepare(`SELECT id FROM developer_api_keys WHERE request_id=?1`).bind(payload.request_id).first();if(exists)return reply({error:'request_already_used'},409);
    const raw=`at_${environment}_${randomToken(32)}`;const hash=await sha256Hex(raw);const id=`key_${hash.slice(0,24)}`;const now=new Date().toISOString();
    await env.DB.prepare(`INSERT INTO developer_api_keys (id,request_id,owner_passport_id,key_hash,key_prefix,environment,scopes_json,status,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,'active',?8,?8)`).bind(id,payload.request_id,passport.id,hash,raw.slice(0,18),environment,JSON.stringify(scopes),now).run();
    return reply({api_key:{id,environment,scopes,prefix:raw.slice(0,18),token:raw,created_at:now},warning:'This token is returned once. Store it securely; AccordTrace stores only its SHA-256 hash.'},201);
  }
  if(request.method==='POST'&&url.pathname==='/api/v1/developer/keys/revoke'){
    const b=await bodyJson(request);required(b.key_id,'key_id');required(b.passport_id,'passport_id');required(b.revoked_at,'revoked_at');required(b.signature,'signature');assertFresh(b.revoked_at);const row=await env.DB.prepare(`SELECT id,owner_passport_id,status FROM developer_api_keys WHERE id=?1`).bind(cleanId(b.key_id)).first();if(!row)return reply({error:'api_key_not_found'},404);if(row.owner_passport_id!==String(b.passport_id))return reply({error:'owner_mismatch'},403);const passport=await activePassport(env,b.passport_id);if(!passport)return reply({error:'passport_not_found'},404);const payload={domain:'accordtrace.developer.api_key.revoke.v1',key_id:row.id,passport_id:passport.id,revoked_at:new Date(b.revoked_at).toISOString()};await verifyEd25519(passport.public_key,canonicalize(payload),b.signature);await env.DB.prepare(`UPDATE developer_api_keys SET status='revoked',revoked_at=?1,updated_at=?1 WHERE id=?2 AND status='active'`).bind(payload.revoked_at,row.id).run();return reply({key_id:row.id,status:'revoked'});
  }
  if(request.method==='GET'&&url.pathname==='/api/v1/developer/test/ping'){
    const auth=await authenticateDeveloperKey(request,env,'test:read',{environment:'test'});if(!auth.ok)return reply({error:auth.error},auth.status);return reply({ok:true,mode:'test',passport_id:auth.owner_passport_id,key_id:auth.key_id,scope:'test:read'});
  }
  return reply({error:'not_found'},404);
}
export async function authenticateDeveloperKey(request,env,scope,options={}){const h=request.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return{ok:false,status:401,error:'api_key_required'};const raw=h.slice(7).trim();if(!/^at_(test|live)_[A-Za-z0-9_-]{20,}$/.test(raw))return{ok:false,status:401,error:'invalid_api_key'};const hash=await sha256Hex(raw);const row=await env.DB.prepare(`SELECT id,owner_passport_id,environment,scopes_json,status FROM developer_api_keys WHERE key_hash=?1`).bind(hash).first();if(!row||row.status!=='active')return{ok:false,status:401,error:'invalid_api_key'};if(options.environment&&row.environment!==options.environment)return{ok:false,status:403,error:'wrong_environment'};let scopes=[];try{scopes=JSON.parse(row.scopes_json||'[]')}catch{}if(scope&&!scopes.includes(scope))return{ok:false,status:403,error:'scope_not_granted'};await env.DB.prepare(`UPDATE developer_api_keys SET last_used_at=?1,updated_at=?1 WHERE id=?2`).bind(new Date().toISOString(),row.id).run();return{ok:true,key_id:row.id,owner_passport_id:row.owner_passport_id,environment:row.environment,scopes};}
function normalizeScopes(v){const scopes=[...new Set((Array.isArray(v)?v:[]).map(x=>String(x).trim()).filter(x=>ALL_SCOPES.has(x)))].sort();if(!scopes.length)scopes.push('test:read');return scopes}
async function activePassport(env,id){const s=String(id||'').trim();if(!s)return null;return env.DB.prepare(`SELECT id,public_key,status FROM agent_passports WHERE id=?1 AND status='active'`).bind(s).first()}
function randomToken(bytes){const b=crypto.getRandomValues(new Uint8Array(bytes));return btoa(String.fromCharCode(...b)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function cleanId(v){const s=String(v||'').trim();if(!/^[A-Za-z0-9][A-Za-z0-9._:-]{0,199}$/.test(s))throw new DeveloperError('invalid_id',400);return s}function required(v,n){if(!String(v??'').trim())throw new DeveloperError(`${n} is required`,400)}function assertFresh(v){const t=Date.parse(v);if(!Number.isFinite(t)||Math.abs(Date.now()-t)>MAX_SKEW)throw new DeveloperError('timestamp_out_of_range',400)}
async function verifyEd25519(pem,msg,sig){let k;try{k=await crypto.subtle.importKey('spki',pemBytes(pem),{name:'Ed25519'},false,['verify'])}catch{throw new DeveloperError('invalid_public_key',422)}let ok=false;try{ok=await crypto.subtle.verify({name:'Ed25519'},k,b64(sig),new TextEncoder().encode(msg))}catch{}if(!ok)throw new DeveloperError('signature_verification_failed',401)}function pemBytes(p){const b=String(p||'').replace(/-----BEGIN PUBLIC KEY-----|-----END PUBLIC KEY-----|\s/g,'');return Uint8Array.from(atob(b),c=>c.charCodeAt(0))}function b64(v){const n=String(v||'').replace(/-/g,'+').replace(/_/g,'/');return Uint8Array.from(atob(n+'='.repeat((4-n.length%4)%4)),c=>c.charCodeAt(0))}
function canonicalize(v){if(v===null||typeof v==='boolean'||typeof v==='string'||typeof v==='number')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonicalize).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonicalize(v[k])}`).join(',')}}`}async function sha256Hex(v){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v)));return[...new Uint8Array(d)].map(x=>x.toString(16).padStart(2,'0')).join('')}async function bodyJson(r){try{return await r.json()}catch{throw new DeveloperError('request_body_must_be_json',400)}}function reply(b,s=200){return new Response(JSON.stringify(b),{status:s,headers:JSON_HEADERS})}export class DeveloperError extends Error{constructor(message,status=400){super(message);this.status=status}}
