const statusEl=document.getElementById('stats-status');
const summaryEl=document.getElementById('stats-summary');
const agentSummaryEl=document.getElementById('agent-summary');
const agentNoteEl=document.getElementById('agent-stats-note');
const affiliateSummaryEl=document.getElementById('affiliate-summary');
const affiliateNoteEl=document.getElementById('affiliate-stats-note');
const headEl=document.getElementById('stats-head');
const bodyEl=document.getElementById('stats-body');

const label=(name)=>name.replaceAll('_',' ').replace(/\b\w/g,(m)=>m.toUpperCase());
const number=(value)=>Number(value??0).toLocaleString();
const money=(atomic,currency='usd')=>new Intl.NumberFormat(undefined,{style:'currency',currency:String(currency).toUpperCase()}).format(Number(atomic??0)/100);

function statCard(name,value){const card=document.createElement('article');card.className='stat-card';const strong=document.createElement('strong');strong.textContent=String(value);const span=document.createElement('span');span.textContent=name;card.append(strong,span);return card;}

function renderAgentMetrics(data){const agents=data.agents??data.agentMetrics??null;if(!agents){agentNoteEl.textContent='Agent identity counting is not active on this deployment yet. Service usage below remains accurate, but it must not be presented as a unique-agent count.';return;}const active=agents.active??agents.identified??{};const requests=agents.requests??{};const protocols=agents.protocols??{};const cards=[['Active agents · 24h',number(active.active24h??active.daily??0)],['Active agents · 7d',number(active.active7d??active.weekly??0)],['Active agents · 30d',number(active.active30d??active.monthly??0)],['New agents · 7d',number(active.new7d??0)],['Returning agents · 7d',number(active.returning7d??0)],['Identified requests',number(requests.identified??0)],['Anonymous requests',number(requests.anonymous??0)]];for(const [protocol,value] of Object.entries(protocols))cards.push([`${protocol.toUpperCase()} requests`,number(value)]);agentSummaryEl.hidden=false;agentSummaryEl.replaceChildren(...cards.map(([name,value])=>statCard(name,value)));agentNoteEl.textContent=agents.note??'Unique-agent figures count pseudonymous client identifiers only. Anonymous requests are reported separately.';}

function renderAffiliateMetrics(data){const a=data.attributions??{},c=data.commissions??{},p=data.affiliates??{},i=data.invitation_payloads??{};const currency=data.currency??'usd';const conversion=Number(data.conversions?.attribution_to_qualified_sale??0);const cards=[['Active affiliates',number(p.active)],['Generated invites · 30d',number(i.last_30d)],['Direct attributions',number(a.total)],['Qualified direct sales',number(a.qualified_direct_sales)],['Held for review',number(a.held)],['Earned commissions',number(c.earned)],['Actually paid commissions',number(c.paid)],['Earned amount',money(c.earned_amount_atomic,currency)],['Actually paid amount',money(c.paid_amount_atomic,currency)],['Attribution → sale',`${(conversion*100).toFixed(1)}%`]];affiliateSummaryEl.hidden=false;affiliateSummaryEl.replaceChildren(...cards.map(([name,value])=>statCard(name,value)));affiliateNoteEl.textContent=`Launch economics: ${money(data.passport_price_atomic,currency)} Passport / ${money(data.direct_commission_atomic,currency)} direct qualifying commission. ${data.boundary??'Invitation counts are not sales.'}`;}

async function loadStats(){try{const [serviceResponse,affiliateResponse]=await Promise.all([fetch('/v1/stats',{headers:{accept:'application/json'}}),fetch('/api/v1/network/stats',{headers:{accept:'application/json'}})]);if(!serviceResponse.ok)throw new Error(`Service stats HTTP ${serviceResponse.status}`);const data=await serviceResponse.json();if(affiliateResponse.ok)renderAffiliateMetrics(await affiliateResponse.json());else affiliateNoteEl.textContent=`Affiliate statistics are temporarily unavailable (HTTP ${affiliateResponse.status}). No referral activity is inferred from missing data.`;const totals=data.totals??{};const daily=Array.isArray(data.daily)?data.daily:[];const events=[...new Set([...Object.keys(totals),...daily.flatMap((row)=>Object.keys(row).filter((key)=>key!=='day'))])].sort();renderAgentMetrics(data);statusEl.textContent=`Live aggregate window: ${data.windowDays??30} days. Last refreshed ${new Date().toLocaleString()}.`;summaryEl.hidden=false;summaryEl.replaceChildren(...events.map((event)=>statCard(label(event),number(totals[event]))));for(const event of events){const th=document.createElement('th');th.textContent=label(event);headEl.append(th);}for(const row of daily){const tr=document.createElement('tr');const date=document.createElement('td');date.textContent=row.day;tr.append(date);for(const event of events){const td=document.createElement('td');td.textContent=number(row[event]);tr.append(td);}bodyEl.append(tr);}if(!events.length)statusEl.textContent+=' No production events have been recorded in this window yet.';}catch(error){statusEl.textContent=`Live statistics are temporarily unavailable (${error.message}). The Accord Trace service can continue operating independently of this dashboard.`;agentNoteEl.textContent='Agent adoption statistics are temporarily unavailable with the service statistics endpoint.';affiliateNoteEl.textContent='Affiliate statistics are temporarily unavailable. No sales, commissions or referrals are inferred from missing data.';}}

loadStats();
