const productRoot=document.querySelector('#products');const statsRoot=document.querySelector('#stats');const stripeStatus=document.querySelector('#stripe-market-status');const dialog=document.querySelector('#checkout-dialog');const checkoutForm=document.querySelector('#checkout-form');const checkoutProduct=document.querySelector('#checkout-product');const checkoutPassport=document.querySelector('#checkout-passport');const checkoutRef=document.querySelector('#checkout-subject-ref');const checkoutTitle=document.querySelector('#checkout-title');const checkoutState=document.querySelector('#checkout-state');let stripe={commercial_ready:false,price_configured:{}};let products=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function get(path){const r=await fetch(path,{headers:{accept:'application/json'}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||b.error||`HTTP ${r.status}`);return b;}
async function load(){
  try{stripe=await get('/api/v1/launch/stripe/capabilities');stripeStatus.textContent=stripe.commercial_ready?'Secure Stripe Checkout is available for configured validation types.':'Card payments are prepared but intentionally disabled until Stripe secrets and Price IDs are connected.';}catch{stripeStatus.textContent='Card payments are not deployed yet; agent/x402 and public evidence flows remain separate.';}
  try{({products=[]}=await get('/api/v1/validation/products'));productRoot.innerHTML=products.length?products.map(p=>productCard(p)).join(''):'<p>No active validation products yet.</p>';}catch(e){productRoot.textContent=`Products unavailable: ${e.message}`;}
  try{const s=await get('/api/v1/validation/stats');statsRoot.innerHTML=`<div class="card"><p><strong>${s.products.active}</strong> active products · <strong>${s.requests.total}</strong> paid requests · <strong>${s.requests.completed}</strong> completed</p><p>Passed ${s.outcomes.passed} · Failed ${s.outcomes.failed} · Inconclusive ${s.outcomes.inconclusive}</p><p>${s.participants.distinct_subject_passports} subject Passports · ${s.participants.distinct_validator_passports} validator Passports</p><p>DNS challenges: ${s.domain_challenges.verified}/${s.domain_challenges.issued} verified</p><small>${esc(s.privacy)}</small></div>`;}catch(e){statsRoot.textContent=`Metrics unavailable: ${e.message}`;}
}
function productCard(p){const cardReady=Boolean(stripe.commercial_ready&&stripe.price_configured?.[p.validation_type]);return `<article class="card"><p class="eyebrow">${esc(p.validation_type)}</p><h3>${esc(p.title)}</h3><p>${esc(p.description||'Independent validation assessment')}</p><p><strong>Validator:</strong> <code>${esc(p.validator_passport_id)}</code></p><p><strong>Validity:</strong> ${esc(p.validity_days)} days</p>${p.price?`<p><strong>Agent rail:</strong> ${esc(p.price.amount_atomic)} atomic units · ${esc(p.price.asset)} · ${esc(p.price.network)}</p>`:''}<div style="margin-top:auto">${cardReady?`<button class="btn primary" type="button" data-stripe-product="${esc(p.id)}">Pay with Stripe</button>`:'<span class="muted">Stripe checkout pending configuration</span>'}</div></article>`}
productRoot?.addEventListener('click',e=>{const b=e.target.closest('[data-stripe-product]');if(!b)return;const p=products.find(x=>x.id===b.dataset.stripeProduct);if(!p)return;checkoutProduct.value=p.id;checkoutTitle.textContent=p.title;checkoutState.textContent='';dialog.showModal();});
document.querySelector('#checkout-close')?.addEventListener('click',()=>dialog.close());
checkoutForm?.addEventListener('submit',async e=>{e.preventDefault();checkoutState.className='status';checkoutState.textContent='Creating secure Checkout Session…';try{const r=await fetch('/api/v1/launch/stripe/checkout',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({product_id:checkoutProduct.value,subject_passport_id:checkoutPassport.value.trim(),subject_ref:checkoutRef.value.trim()})});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.message||b.error||`HTTP ${r.status}`);if(!/^https:\/\/checkout\.stripe\.com\//.test(b.checkout_url)&&!/^https:\/\//.test(b.checkout_url))throw new Error('Unexpected Checkout URL');checkoutState.className='status ok';checkoutState.textContent='Redirecting to Stripe…';location.assign(b.checkout_url);}catch(err){checkoutState.className='status bad';checkoutState.textContent=err.message;}});
load();